### ISSUE TITLE
measure-metrics folder missing

### ISSUE THREAD

**Issue by karthickai** [te42kyfo/cuda-benches#2]
Could you kindly share the measure metrics folder? Because unable to build the Cuda-l2-cache benchmark.

**Comment by te42kyfo** [comment]
Hm, that particular benchmark should not use any metric measurement at all, and I haven't seen any leftover includes. I have included the files anyway, because other benchmarks do measure metrics.

The measure_metrics folder used to be a separate repository, but I  included the files directly now.

Out if curiosity, your are interested in L2 cache read/write bandwidths?

**Comment by karthickai** [comment]
Hi @te42kyfo, Thank you immediate response. Yes, I try to get an L2 cache read/write. It's working fine now. Note: I already got the L2 throughput using your Cuda-cache program. Thanks for your excellent work.
